/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/users/{id}": {
    get: operations["getUser"];
    put: operations["updateUser"];
    delete: operations["deleteUser"];
  };
  "/api/v1/users": {
    post: operations["createUser"];
  };
  "/health": {
    /**
     * Public health check
     * @description Returns application health status without requiring authentication. Suitable for load balancers, Kubernetes probes, and monitoring systems that cannot provide JWT tokens.
     */
    get: operations["healthcheck"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    UserRequest: {
      /**
       * @description User's unique identifier
       * @example user_123
       */
      id: string;
      /**
       * @description User's first name
       * @example John
       */
      firstName: string;
      /**
       * @description User's last name
       * @example Doe
       */
      lastName?: string;
      /**
       * @description User's email address
       * @example john.doe@example.com
       */
      email: string;
    };
    UserResponse: {
      /**
       * @description User's unique identifier
       * @example user_123
       */
      id?: string;
      /**
       * @description User's first name
       * @example John
       */
      firstName?: string;
      /**
       * @description User's last name
       * @example Doe
       */
      lastName?: string;
      /**
       * @description User's email address
       * @example john.doe@example.com
       */
      email?: string;
      /**
       * Format: date-time
       * @description Timestamp when the user was created
       */
      createdAt?: string;
      /**
       * Format: date-time
       * @description Timestamp when the user was last updated
       */
      updatedAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  getUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  deleteUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
    };
  };
  createUser: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  /**
   * Public health check
   * @description Returns application health status without requiring authentication. Suitable for load balancers, Kubernetes probes, and monitoring systems that cannot provide JWT tokens.
   */
  healthcheck: {
    responses: {
      /** @description Health status returned */
      200: {
        content: {
          "*/*": string;
        };
      };
      /** @description Server error */
      500: {
        content: never;
      };
    };
  };
}
